version: '3'
services:
  zulip_sync:
    build:
      context: .
    image: ragnaruk/api_integration:latest
    restart: always
    command: ['python', '/api_integration/scenarios/sync_groups_and_zulip.py']